// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/dicearcade/v1/gamemanager.proto

package gamemanagerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_api_dicearcade_v1_gamemanager_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_api_dicearcade_v1_gamemanager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayOnceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayOnceRequest) Reset() {
	*x = PlayOnceRequest{}
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayOnceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayOnceRequest) ProtoMessage() {}

func (x *PlayOnceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayOnceRequest.ProtoReflect.Descriptor instead.
func (*PlayOnceRequest) Descriptor() ([]byte, []int) {
	return file_api_dicearcade_v1_gamemanager_proto_rawDescGZIP(), []int{2}
}

func (x *PlayOnceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlayOnceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayOnceResponse) Reset() {
	*x = PlayOnceResponse{}
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayOnceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayOnceResponse) ProtoMessage() {}

func (x *PlayOnceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dicearcade_v1_gamemanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayOnceResponse.ProtoReflect.Descriptor instead.
func (*PlayOnceResponse) Descriptor() ([]byte, []int) {
	return file_api_dicearcade_v1_gamemanager_proto_rawDescGZIP(), []int{3}
}

func (x *PlayOnceResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_api_dicearcade_v1_gamemanager_proto protoreflect.FileDescriptor

const file_api_dicearcade_v1_gamemanager_proto_rawDesc = "" +
	"\n" +
	"#api/dicearcade/v1/gamemanager.proto\x12\rdicearcade.v1\"'\n" +
	"\x11CreateGameRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"8\n" +
	"\x12CreateGameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"!\n" +
	"\x0fPlayOnceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x10PlayOnceResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome2\xad\x01\n" +
	"\vGameManager\x12Q\n" +
	"\n" +
	"CreateGame\x12 .dicearcade.v1.CreateGameRequest\x1a!.dicearcade.v1.CreateGameResponse\x12K\n" +
	"\bPlayOnce\x12\x1e.dicearcade.v1.PlayOnceRequest\x1a\x1f.dicearcade.v1.PlayOnceResponseB-Z+dice-arcade/api/dicearcade/v1;gamemanagerpbb\x06proto3"

var (
	file_api_dicearcade_v1_gamemanager_proto_rawDescOnce sync.Once
	file_api_dicearcade_v1_gamemanager_proto_rawDescData []byte
)

func file_api_dicearcade_v1_gamemanager_proto_rawDescGZIP() []byte {
	file_api_dicearcade_v1_gamemanager_proto_rawDescOnce.Do(func() {
		file_api_dicearcade_v1_gamemanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dicearcade_v1_gamemanager_proto_rawDesc), len(file_api_dicearcade_v1_gamemanager_proto_rawDesc)))
	})
	return file_api_dicearcade_v1_gamemanager_proto_rawDescData
}

var file_api_dicearcade_v1_gamemanager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_dicearcade_v1_gamemanager_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: dicearcade.v1.CreateGameRequest
	(*CreateGameResponse)(nil), // 1: dicearcade.v1.CreateGameResponse
	(*PlayOnceRequest)(nil),    // 2: dicearcade.v1.PlayOnceRequest
	(*PlayOnceResponse)(nil),   // 3: dicearcade.v1.PlayOnceResponse
}
var file_api_dicearcade_v1_gamemanager_proto_depIdxs = []int32{
	0, // 0: dicearcade.v1.GameManager.CreateGame:input_type -> dicearcade.v1.CreateGameRequest
	2, // 1: dicearcade.v1.GameManager.PlayOnce:input_type -> dicearcade.v1.PlayOnceRequest
	1, // 2: dicearcade.v1.GameManager.CreateGame:output_type -> dicearcade.v1.CreateGameResponse
	3, // 3: dicearcade.v1.GameManager.PlayOnce:output_type -> dicearcade.v1.PlayOnceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_dicearcade_v1_gamemanager_proto_init() }
func file_api_dicearcade_v1_gamemanager_proto_init() {
	if File_api_dicearcade_v1_gamemanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dicearcade_v1_gamemanager_proto_rawDesc), len(file_api_dicearcade_v1_gamemanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dicearcade_v1_gamemanager_proto_goTypes,
		DependencyIndexes: file_api_dicearcade_v1_gamemanager_proto_depIdxs,
		MessageInfos:      file_api_dicearcade_v1_gamemanager_proto_msgTypes,
	}.Build()
	File_api_dicearcade_v1_gamemanager_proto = out.File
	file_api_dicearcade_v1_gamemanager_proto_goTypes = nil
	file_api_dicearcade_v1_gamemanager_proto_depIdxs = nil
}
