// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/dicearcade/v1/gamemanager.proto

package gamemanagerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameManager_CreateGame_FullMethodName   = "/dicearcade.v1.GameManager/CreateGame"
	GameManager_PlayOnce_FullMethodName     = "/dicearcade.v1.GameManager/PlayOnce"
	GameManager_GetSummary_FullMethodName   = "/dicearcade.v1.GameManager/GetSummary"
	GameManager_JoinGame_FullMethodName     = "/dicearcade.v1.GameManager/JoinGame"
	GameManager_PlayTurn_FullMethodName     = "/dicearcade.v1.GameManager/PlayTurn"
	GameManager_GetGameState_FullMethodName = "/dicearcade.v1.GameManager/GetGameState"
)

// GameManagerClient is the client API for GameManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameManagerClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	PlayOnce(ctx context.Context, in *PlayOnceRequest, opts ...grpc.CallOption) (*PlayOnceResponse, error)
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GameSummaryResponse, error)
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error)
	PlayTurn(ctx context.Context, in *PlayTurnRequest, opts ...grpc.CallOption) (*PlayTurnResponse, error)
	GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error)
}

type gameManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameManagerClient(cc grpc.ClientConnInterface) GameManagerClient {
	return &gameManagerClient{cc}
}

func (c *gameManagerClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, GameManager_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManagerClient) PlayOnce(ctx context.Context, in *PlayOnceRequest, opts ...grpc.CallOption) (*PlayOnceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayOnceResponse)
	err := c.cc.Invoke(ctx, GameManager_PlayOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManagerClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GameSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameSummaryResponse)
	err := c.cc.Invoke(ctx, GameManager_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManagerClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGameResponse)
	err := c.cc.Invoke(ctx, GameManager_JoinGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManagerClient) PlayTurn(ctx context.Context, in *PlayTurnRequest, opts ...grpc.CallOption) (*PlayTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayTurnResponse)
	err := c.cc.Invoke(ctx, GameManager_PlayTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameManagerClient) GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStateResponse)
	err := c.cc.Invoke(ctx, GameManager_GetGameState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameManagerServer is the server API for GameManager service.
// All implementations must embed UnimplementedGameManagerServer
// for forward compatibility.
type GameManagerServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	PlayOnce(context.Context, *PlayOnceRequest) (*PlayOnceResponse, error)
	GetSummary(context.Context, *GetSummaryRequest) (*GameSummaryResponse, error)
	JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error)
	PlayTurn(context.Context, *PlayTurnRequest) (*PlayTurnResponse, error)
	GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error)
	mustEmbedUnimplementedGameManagerServer()
}

// UnimplementedGameManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameManagerServer struct{}

func (UnimplementedGameManagerServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameManagerServer) PlayOnce(context.Context, *PlayOnceRequest) (*PlayOnceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayOnce not implemented")
}
func (UnimplementedGameManagerServer) GetSummary(context.Context, *GetSummaryRequest) (*GameSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedGameManagerServer) JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedGameManagerServer) PlayTurn(context.Context, *PlayTurnRequest) (*PlayTurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayTurn not implemented")
}
func (UnimplementedGameManagerServer) GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameState not implemented")
}
func (UnimplementedGameManagerServer) mustEmbedUnimplementedGameManagerServer() {}
func (UnimplementedGameManagerServer) testEmbeddedByValue()                     {}

// UnsafeGameManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameManagerServer will
// result in compilation errors.
type UnsafeGameManagerServer interface {
	mustEmbedUnimplementedGameManagerServer()
}

func RegisterGameManagerServer(s grpc.ServiceRegistrar, srv GameManagerServer) {
	// If the following call pancis, it indicates UnimplementedGameManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameManager_ServiceDesc, srv)
}

func _GameManager_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManagerServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManager_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManagerServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManager_PlayOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayOnceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManagerServer).PlayOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManager_PlayOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManagerServer).PlayOnce(ctx, req.(*PlayOnceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManager_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManagerServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManager_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManagerServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManager_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManagerServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManager_JoinGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManagerServer).JoinGame(ctx, req.(*JoinGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManager_PlayTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManagerServer).PlayTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManager_PlayTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManagerServer).PlayTurn(ctx, req.(*PlayTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameManager_GetGameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameManagerServer).GetGameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameManager_GetGameState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameManagerServer).GetGameState(ctx, req.(*GetGameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameManager_ServiceDesc is the grpc.ServiceDesc for GameManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dicearcade.v1.GameManager",
	HandlerType: (*GameManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameManager_CreateGame_Handler,
		},
		{
			MethodName: "PlayOnce",
			Handler:    _GameManager_PlayOnce_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _GameManager_GetSummary_Handler,
		},
		{
			MethodName: "JoinGame",
			Handler:    _GameManager_JoinGame_Handler,
		},
		{
			MethodName: "PlayTurn",
			Handler:    _GameManager_PlayTurn_Handler,
		},
		{
			MethodName: "GetGameState",
			Handler:    _GameManager_GetGameState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/dicearcade/v1/gamemanager.proto",
}
